# included/excluded modules and/or files
included:
    - authTestApp

excluded:
    - Pods
    - authTestApp/AppDelegate.swift
    - authTestApp/SceneDelegate.swift

# rule identifiers turned on by default to exclude from running
disabled_rules:
    - private_over_fileprivate
    - nesting
    - block_based_kvo
